---
# handlers file for apache
  - name: Reload Web
    ansible.builtin.service:
      name: apache2
      state: reloaded
    become: true
  - name: Enable Default SSL Site
    shell: a2ensite default-ssl
    become: true
    when: copydefault.changeds