- name: Reload Web
  ansible.builtin.service:
    name: apache2
    state: reloaded
  become: true
- name: Enable Default SSL Site
  ansible.builtin.shell: a2ensite default-ssl
  become: true
  when: copydefault.changed
