- name: Create required cron jobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    day: "{{ item.day }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    job: "{{ item.job }}"
  become: true
  with_items: "{{ cron_jobs }}"
