- name: Create Cron Job
  ansible.builtin.cron:
    name: "{{ item.name }}"
    day: "{{ item.day }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    job: "{{ item.job }}"
  become: true
  loop: "{{ jobs }}"