# - name: Create Required Directories
#   ansible.builtin.file:
#     path: "{{ item.name }}"
#     owner: "{{ item.owner | default('root') }}"
#     group: "{{ item.group | default('users') }}"
#     mode: "{{ item.mode | default('0644') }}"
#     state: directory
#   loop: "{{ filesystem.directories }}"
#   become: true
#   when: filesystem.directories is defined

- name: Storage Server | Filesystem | Resolve rsync target credentials
  ansible.builtin.set_fact:
    rsync_target_password: "{{ ansible_password }}"
    rsync_target_user: "{{ ansible_user }}"
  no_log: true

- name: Storage Server | Filesystem | Sync Required Files & Directories
  ansible.builtin.shell: >
    sshpass -p '{{ rsync_target_password }}'
    rsync -a --delete -i
    --no-perms --no-owner --no-group --no-times
    -e "ssh -o StrictHostKeyChecking=accept-new"
    {{ playbook_dir }}/{{ item.src }}/
    {{ rsync_target_user }}@{{ inventory_hostname }}:{{ item.dest }}
    --rsync-path="sudo rsync"
  register: rsync_result
  changed_when: >
    rsync_result.stdout_lines
    | select('match', '^[<>ch].f')
    | list
    | length > 0
  loop: "{{ storage_server_filesystem.copy_files }}"
  delegate_to: localhost
  no_log: true
  when:
    - storage_server_filesystem.copy_files is defined

- name: Storage Server | Filesystem | Ensure permissions for synced paths
  ansible.builtin.file:
    path: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    recurse: "{{ item.recurse | default(true) }}"
  loop: "{{ storage_server_filesystem.copy_files }}"
  become: true
  when:
    - storage_server_filesystem.copy_files is defined
