- name: Create Required Directories
  ansible.builtin.file:
    path: "{{ item.name }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('users') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: directory
  loop: "{{ filesystem.directories }}"
  become: true

- name: Copy Required Files & Directories
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('users') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ filesystem.copy_files }}"
  become: true