# - name: Create Required Directories
#   ansible.builtin.file:
#     path: "{{ item.name }}"
#     owner: "{{ item.owner | default('root') }}"
#     group: "{{ item.group | default('users') }}"
#     mode: "{{ item.mode | default('0644') }}"
#     state: directory
#   loop: "{{ filesystem.directories }}"
#   become: true
#   when: filesystem.directories is defined

- name: Storage Server | Filesystem | Copy Required Files & Directories
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ storage_server_filesystem.copy_files }}"
  become: true
  when: storage_server_filesystem.copy_files is defined

