# - name: Create Required Directories
#   ansible.builtin.file:
#     path: "{{ item.name }}"
#     owner: "{{ item.owner | default('root') }}"
#     group: "{{ item.group | default('users') }}"
#     mode: "{{ item.mode | default('0644') }}"
#     state: directory
#   loop: "{{ filesystem.directories }}"
#   become: true
#   when: filesystem.directories is defined

- name: Storage Server | Filesystem | Sync Required Files & Directories
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    recursive: "{{ item.recurse | default(true) }}"
    delete: "{{ item.delete | default(false) }}"
    mode: push
  loop: "{{ storage_server_filesystem.copy_files }}"
  become: true
  when:
    - storage_server_filesystem.copy_files is defined

- name: Storage Server | Filesystem | Ensure permissions for synced paths
  ansible.builtin.file:
    path: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    recurse: "{{ item.recurse | default(true) }}"
  loop: "{{ storage_server_filesystem.copy_files }}"
  become: true
  when:
    - storage_server_filesystem.copy_files is defined

