

- name: File Sharing - Copy Samba Configuration file
  ansible.builtin.copy:
    src: "{{ file_sharing.smb_config_path }}"
    dest: /etc/samba/smb.conf
    owner: root
    group: users
    mode: '0770'
  notify: Restart SMB
  become: true
  when: storage_server_smb_config_path is not none

- name: File Sharing - Copy NFS Exports file
  ansible.builtin.copy:
    src: "{{ file_sharing.nfs_config_path }}"
    dest: /etc/exports
    owner: root
    group: users
    mode: '0770'
  notify: Restart NFS
  become: true
  when: storage_server_nfs_config_path is not none
