- name: Storage Server | Packages | Gather Package Facts
  ansible.builtin.package_facts:
    manager: auto

- name: Storage Server | Packages | Install
  become: true
  ansible.builtin.apt:
    name: "{{ item.name }}" 
  when: "{{ item.when }}"
  with_items: "{{ packages }}"

