- name: Storage Server | Installation
  ansible.builtin.include_tasks: installation.yml
  when: enable_installation
# - name: Include Filesystem Tasks
#   ansible.builtin.include_tasks: filesystem.yml
#   when: filesystem is defined
# - name: Include smb_users
#   ansible.builtin.include_tasks: smb_users.yml
#   when: users is defined

- name: Storage Server | Firewall
  ansible.builtin.include_tasks: firewall.yml
  when:
    - enable_firewall_config
    - "'ufw' in ansible_facts.packages"

- name: Storage Server | ZFS
  ansible.builtin.include_tasks: zfs.yml
  become: true
  when: 
    - enable_zfs_config
    - storage_server_zfs is not none

- name: Storage Server | File Sharing
  ansible.builtin.include_tasks: file_sharing.yml
  when: enable_file_sharing