- name: Storage Server | Gather Package Facts
  ansible.builtin.package_facts:
    manager: auto

- name: Storage Server | ZFS
  ansible.builtin.include_tasks: zfs.yml
  when:
    - enable_zfs_config
    - storage_server_zfs is not none

- name: Storage Server | Permissions
  ansible.builtin.include_tasks: permissions.yml
  when:
    - enable_permissions
    - storage_server_permissions is not none

- name: Include Filesystem Tasks
  ansible.builtin.include_tasks: filesystem.yml
  when:
    - storage_server_filesystem is not none
    - enable_filesystem_tasks

- name: Storage Server | Samba
  ansible.builtin.include_tasks: samba.yml
  when:
    - enable_samba
    - storage_server_smb_config_path is not none

- name: Storage Server | NFS
  ansible.builtin.include_tasks: nfs.yml
  when:
    - enable_nfs
    - storage_server_nfs_config_path is not none

- name: Storage Server | Rclone
  ansible.builtin.include_tasks: rclone.yml
  when:
    - enable_rclone
    - storage_server_rclone_config_path is not none
