- name: Users - Install Required Packages on Ansible host
  apt:
    pkg: python3-passlib
  delegate_to: localhost
  become: true
- name: Users - Add Unix Groups
  ansible.builtin.group:
    name: "{{ item.username }}"
    state: present
    gid: "{{ item.uid }}"
  loop: "{{ users }}"
  become: true
  changed_when: False
  no_log: true
- name: Users - Add Unix Users
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.username }}"
    uid: "{{ item.uid }}"
    shell: /bin/bash
    group: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512') }}"
    append: true
    groups: users
  loop: "{{ users }}"
  changed_when: False
  become: true
  no_log: true
- name: Users - shell - create samba users
  ansible.builtin.shell: >
    set -e -o pipefail
    && (pdbedit --user={{ item.username }} 2>&1 > /dev/null)
    || (echo '{{ item.password }}'; echo '{{ item.password }}')
    | smbpasswd -s -a {{ item.username }}
  args:
    executable: /bin/bash
  loop: "{{ users }}"
  become: true
  no_log: true
  changed_when: False
- name: Users - shell - set samba passwords correctly
  ansible.builtin.shell: >
    set -e -o pipefail
    && (smbclient -U {{ item.username }}%{{ item.password }} -L 127.0.0.1 2>&1 > /dev/null)
    || (echo '{{ item.password }}'; echo '{{ item.password }}')
    | smbpasswd {{ item.username }}
  args:
    executable: /bin/bash
  loop: "{{ users }}"
  become: true
  no_log: true
  changed_when: False
- name: Users - Add Users to Users group
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: users
    append: yes
  loop: "{{ users }}"
  become: true
  no_log: true