- name: Storage Server | ZFS | Create Pools
  community.general.zpool:
    name: "{{ item.name }}"
    vdevs: "{{ item.vdevs }}"
    altroot: "{{ item.altroot | default(omit) }}"
    disable_new_features: "{{ item.disable_new_features | default(false) }}"
    filesystem_properties: "{{ item.filesystem_properties | default({}) }}"
    force: "{{ item.force | default(false) }}"
    mountpoint: "{{ item.mountpoint | default('/mnt/' + item.key) }}"
    pool_properties: "{{ item.pool_properties | default({}) }}"
    state: "{{ item.state | default('present') }}"
    temp_name: "{{ item.temp_name | default(omit) }}"
  when:
    - storage_server_zfs.pools is defined
    - item.vdevs is defined
  loop: "{{ storage_server_zfs.pools }}"
  loop_control:
    label: "{{ item.name }}"
  become: true

- name: Storage Server | ZFS | Create Datasets
  community.general.zfs:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    extra_zfs_properties: "{{ item.extra_zfs_properties | default({}) }}"
  loop: "{{ storage_server_zfs.datasets }}"
  loop_control:
    label: "{{ item.name }}"
  become: true