- name: Storage Server | Permissions | Dataset | Set Unix Permissions
  ansible.builtin.file:
    path: "{{ permission.path | default(dataset_path) }}"
    mode: "{{ permission.mode | default('0770') }}"
    owner: "{{ permission.owner | default('root') }}"
    group: "{{ permission.group | default('root') }}"
  loop: "{{ dataset_permissions }}"
  loop_control:
    loop_var: permission
    label: "{{ permission.path | default(dataset_path) }} | {{ permission.entity | default('') }}"
  when:
    - permission.mode is defined or permission.owner is defined or permission.group is defined
  become: true

- name: Storage Server | Permissions | Dataset | Remove implicit ACL entries
  ansible.builtin.command:
    cmd: "setfacl -R -x {{ permission.etype | first }}:{{ permission.entity }} {{ permission.path | default(dataset_path) }}"
  loop: "{{ dataset_permissions }}"
  loop_control:
    loop_var: permission
    label: "{{ permission.path | default(dataset_path) }} | {{ permission.entity | default('') }}"
  when:
    - permission.entity is defined
    - permission.state | default('present') == 'absent'
  become: true
  changed_when: true

- name: Storage Server | Permissions | Dataset | Remove default ACL entries
  ansible.builtin.command:
    cmd: "setfacl -R -x d:{{ permission.etype | first }}:{{ permission.entity }} {{ permission.path | default(dataset_path) }}"
  loop: "{{ dataset_permissions }}"
  loop_control:
    loop_var: permission
    label: "{{ permission.path | default(dataset_path) }} | {{ permission.entity | default('') }}"
  when:
    - permission.entity is defined
    - permission.state | default('present') == 'absent'
  become: true
  changed_when: true

- name: Storage Server | Permissions | Dataset | Configure implicit ACL
  ansible.posix.acl:
    path: "{{ permission.path | default(dataset_path) }}"
    entity: "{{ permission.entity }}"
    etype: "{{ permission.etype | default('group') }}"
    permissions: "{{ permission.permissions | default(omit) }}"
    default: false
    state: "{{ permission.state | default('present') }}"
    recursive: "{{ permission.recursive | default(true) }}"
  loop: "{{ dataset_permissions }}"
  loop_control:
    loop_var: permission
    label: "{{ permission.path | default(dataset_path) }} | {{ permission.entity | default('') }}"
  when:
    - permission.entity is defined
    - permission.permissions is defined
  become: true

- name: Storage Server | Permissions | Dataset | Configure default ACL
  ansible.posix.acl:
    path: "{{ permission.path | default(dataset_path) }}"
    entity: "{{ permission.entity }}"
    etype: "{{ permission.etype | default('group') }}"
    permissions: "{{ permission.permissions | default(omit) }}"
    default: true
    state: "{{ permission.state | default('present') }}"
    recursive: "{{ permission.recursive | default(true) }}"
  loop: "{{ dataset_permissions }}"
  loop_control:
    loop_var: permission
    label: "{{ permission.path | default(dataset_path) }} | {{ permission.entity | default('') }}"
  when:
    - permission.entity is defined
    - permission.permissions is defined
    - permission.default | default(true)
  become: true
