- name: Docker | Installation | Configure GitHub Packages Authentication
  when: docker_enable_auth
  become: true
  block:
    - name: Docker | Installation | Ensure config directory exists
      ansible.builtin.file:
        path: /root/.docker
        state: directory
        mode: '0770'
    - name: Docker | Installation | Populate docker config from Jinja template
      ansible.builtin.template:
        src: "{{ docker_config_path }}"
        dest: /root/.docker/config.json
        mode: '0770'

- name: Docker | Installation | Populate daemon.json
  ansible.builtin.copy:
    src: "daemon.json"
    dest: /etc/docker/daemon.json
    mode: '0700'
  when: docker_enable_syslog
  notify:
    - Reload Docker
    - Restart Docker