- name: Docker | Volume Data | Copy Files
  ansible.builtin.copy:
    src: "{{ item.1.src }}"
    dest: "{{ item.1.dest }}"
    mode: "{{ item.1.mode | default('0644') }}"
    owner: "{{ item.1.owner | default(1000) }}"
    group: "{{ item.1.group | default(1000) }}"
  loop: "{{ docker_compose_projects | subelements('volume_data', skip_missing=True) }}"
  register: volume_data_copy
  when: not item.template | default(false)

- name: Docker | Volume Data | Template Files
  ansible.builtin.template:
    src: "{{ item.1.src }}"
    dest: "{{ item.1.dest }}"
    mode: "{{ item.1.mode | default('0644') }}"
    owner: "{{ item.1.owner | default(1000) }}"
    group: "{{ item.1.group | default(1000) }}"
  loop: "{{ docker_compose_projects | subelements('volume_data', skip_missing=True) }}"
  register: volume_data_copy
  when: item.template | default(false)

- name: Docker | Volume Data | Restart Containers
  ansible.builtin.shell: "docker restart {{ item.item[1].restart_container }}"
  with_items: "{{ volume_data_copy.results }}"
  when:
    - item.item[1].restart_container is defined
    - item.changed
  loop_control:
    label: "{{ item.item[1].restart_container | default(item.item[0].name)}}"