- name: Docker | Deploy Config | Check for config.json.j2
  ansible.builtin.stat:
    path: "{{ docker_config_path }}/config.json.j2"
  register: config_json
  delegate_to: localhost

- name: Docker | Installation | Configure GitHub Packages Authentication
  when: config_json.stat.exists
  become: true
  block:
    - name: Docker | Installation | Ensure config directory exists
      ansible.builtin.file:
        path: /root/.docker
        state: directory
        mode: '0770'
    - name: Docker | Installation | Populate docker config from Jinja template
      ansible.builtin.template:
        src: "{{ docker_config_path }}/config.json.j2"
        dest: /root/.docker/config.json
        mode: '0770'

- name: Docker | Installation | Create Maintenance Cron Job
  ansible.builtin.cron:
    name: "docker maintenance"
    minute: "0"
    hour: "05"
    job: "docker image prune -f -a"
  become: true

- name: Docker | Installation | Add users to Docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  become: true
  with_items: "{{ docker_users }}"