- name: Docker | Volume Data | Copy Files
  ansible.builtin.copy:
    src: "{{ docker_volume_data_path }}/{{ item.0.name }}/{{ item.1.volume}}/{{ item.1.src }}"
    dest: "_data/{{ item.1.dest | default('/') }}"
    mode: "{{ item.1.mode | default('0644') }}"
    owner: "{{ item.1.owner | default(1000) }}"
    group: "{{ item.1.group | default(1000) }}"
  loop: "{{ docker_compose_projects | subelements('volume_data', skip_missing=True) }}"
  register: volume_data_copy
  loop_control:
    label: "{{ item.1.src }} -> {{ item.0.name }}_{{ item.1.volume }}"

- name: Docker | Volume Data | Restart Containers
  ansible.builtin.shell: "docker restart {{ item.item[1].restart_container }}"
  with_items: "{{ volume_data_copy.results }}"
  when:
    - item.item[1].restart_container is defined
    - item.changed
  loop_control:
    label: "{{ item.item[1].restart_container | default(item.item[0].name)}}"