- name: Docker | Configuration | Deploy Projects | Get Required Projects
  ansible.builtin.shell: ls "{{ docker_config_path }}/compose" | sed 's/\.[^.]*$//' | sed 's/\.[^.]*$//'
  register: applications
  delegate_to: localhost
  become: true
  changed_when: false

- name: Docker | Configuration | Deploy Projects | Create Directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: docker
    mode: '0770'
    state: directory
  become: true
  with_items: "{{ docker.paths.values() | list + docker_dirs | product(applications.stdout_lines) | map('join', '/') | list }}"
  vars:
    docker_dirs:
      - "{{ docker.paths.volumes }}"
      - "{{ docker.paths.apps }}"

- name: Docker | Configuration | Deploy Projects | Set Additional ACL
  ansible.posix.acl:
    path: "{{ item }}"
    entity: "{{ docker_management_group }}"
    etype: group
    permissions: rwx
    default: true
    state: absent
  become: true
  when: docker_management_group is not none
  with_items: "{{ docker.paths.values() | list + docker_dirs | product(applications.stdout_lines) | map('join', '/') | list }}"
  vars:
    docker_dirs:
      - "{{ docker.paths.volumes }}"
      - "{{ docker.paths.apps }}"

- name: Docker | Configuration | Deploy Projects | Set Additional ACL
  ansible.posix.acl:
    path: "{{ item }}"
    entity: "{{ docker_management_group }}"
    etype: group
    permissions: rwx
    default: false
    state: present
  become: true
  when: docker_management_group is not none
  with_items: "{{ docker.paths.values() | list + docker_dirs | product(applications.stdout_lines) | map('join', '/') | list }}"
  vars:
    docker_dirs:
      - "{{ docker.paths.volumes }}"
      - "{{ docker.paths.apps }}"

- name: Docker | Configuration | Deploy Projects | Generate Compose Files
  ansible.builtin.template:
    src: "{{ docker_config_path }}/compose/{{ item }}.yml.j2"
    dest: "{{ docker.paths.apps }}/{{ item }}/compose.yaml"
    owner: root
    group: docker
    mode: '0770'
  with_items: "{{ applications.stdout_lines }}"
  become: true
  register: compose

- name: Docker | Configuration | Deploy Projects | Start Compose Projects
  community.docker.docker_compose_v2:
    project_name: "{{ item.item }}"
    project_src: "{{ docker.paths.apps }}/{{ item.item }}"
    remove_orphans: true
    build: never
    state: present
  tags: docker
  become: true
  with_items: "{{ compose.results }}"
#  when: item.changed
  loop_control:
    label: "{{ item.item }}"
