- name: Docker | Configuration | Destroy Projects | Get Active Compose Projects
  ansible.builtin.shell: "docker compose ls -q"
  register: currentapplications
  become: true
  changed_when: false

- name: Docker | Configuration | Destroy Projects | Stop non-required projects
  ansible.builtin.shell: "docker compose -p {{ item }} down"
  with_items: "{{ currentapplications | difference(applications) }}"
  become: true

- name: Docker | Configuration | Destroy Projects | Remove non-required projects
  ansible.builtin.file:
    path: "/var/lib/docker/compose/{{ item }}"
    state: absent
  become: true
  with_items: "{{ currentapplications | difference(applications) }}"
  # Add conditional logic to remove volumes here?