- name: Docker | Installation | Create Group
  ansible.builtin.group:
    name: docker
    state: present
    gid: 121
  become: true

- name: Docker | Installation | Add current user to Group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true

- name: Docker | Installation | Add nagios user to Group
  ansible.builtin.user:
    name: nagios
    groups: docker
    append: true
  become: true

- name: Docker | Installation | APT | Add APT GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Docker | Installation | APT |  Add Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   jammy stable"
    state: present
    filename: docker

- name: Docker | Installation | APT |  Install Packages
  ansible.builtin.apt:
    pkg: "{{ docker_packages }}"

- name: Docker | Installation | Enable and Start Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: Docker | Installation | Copy ctop binary # need to make this multi arch
  ansible.builtin.copy:
    src: ctop
    dest: /usr/local/bin/ctop
    mode: '0755'
  become: true

- name: Docker | Installation | Create Maintenance Cron Job
  ansible.builtin.cron:
    name: "docker maintenance"
    minute: "0"
    hour: "05"
    job: "docker image prune -f && docker volume prune -f"
  become: true

- name: Docker | Installation | Configure GitHub Packages Authentication
  when: docker_github_auth.enabled # TODO: Make this dynamic
  become: true
  block:
    - name: Docker | Installation | Ensure config directory exists
      ansible.builtin.file:
        path: /root/.docker
        state: directory
        mode: '0770'
    - name: Docker | Installation | Populate docker config from Jinja template
      ansible.builtin.template:
        src: "config.json.j2"
        dest: /root/.docker/config.json
        mode: '0770'

