- name: Global_System | Cloud Init | Copy Config File
  ansible.builtin.copy:
    src: "{{ global_system.cloud_config_path }}"
    dest: /etc/cloud/
    mode: 0644
  notify: Restart Cloud Init

- name: Global_System | Cloud Init | Remove sudoers File
  ansible.builtin.file:
    path: /etc/sudoers.d/90-cloud-init-users
    state: absent
