- name: Global_System | Config | Copy Files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  with_items: "{{ global_system_server_config }}"
  register: copy_files
  when:
    - item.src is defined
    - item.dest is defined
    - item.mode is defined
    - not item.template | default(false)

- name: Global_System | Config | Template Files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  with_items: "{{ global_system_server_config }}"
  register: template_files
  when:
    - item.src is defined
    - item.dest is defined
    - item.mode is defined
    - item.template | default(false)

- name: Global_System | Config | Delete Files
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: absent
  with_items: "{{ global_system_server_config }}"
  register: delete_files
  when:
    - item.dest is defined
    - item.delete

- name: Global_System | Config | Reload Service
  ansible.builtin.systemd:
    name: "{{ item.item.svc_reload }}"
    state: reloaded
    enabled: true
  with_items: "{{ copy_files.results + template_files.results }}"
  register: reload_service
  when:
    - item.changed
    - item.item.svc_reload is defined

- name: Global_System | Config | Reload Service
  ansible.builtin.systemd:
    name: "{{ item.item.svc_restart }}"
    state: restarted
    enabled: true
  with_items: "{{ copy_files.results + template_files.results }}"
  register: restart_service
  when:
    - item.changed
    - item.item.svc_restart is defined