- name: Misc | Delete
  ansible.builtin.file:
    path: /root/register-host.sh
    state: absent
- name: Misc | Delete DNS Registration Cron Job
  ansible.builtin.cron:
    name: "DNS Registration"
    state: absent