- name: Global_System | UFW | Allow SSH
  community.general.ufw:
    rule: allow
    port: 22
    protocol: any
    insert: 100
- name: Global_System | UFW | Enable and set default deny rule
  community.general.ufw:
    state: enabled
    policy: deny
