- name: Global_System | UFW | Enable and set default deny rule
  community.general.ufw:
    state: enabled
    policy: deny
- name: Global_System | UFW | Create Rules
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    protocol: "{{ item.protocol | default('any') }}"
  with_items: "{{ firewall_ports + global_system_firewall_ports | default([]) }}"
