- name: Global_System | Journald | Copy Config File
  ansible.builtin.copy:
    src: "{{ global_system_journald_config_path }}"
    dest: /etc/systemd/journald.conf
    mode: 0644
  notify: Restart Journald
