- name: Install Packages
  ansible.builtin.apt:
    package:
      - nagios-nrpe-server
  when: ansible_facts.distribution_version == "24.04"

- name: Uninstall Packages
  ansible.builtin.apt:
    package:
      - nagios-nrpe-server
    state: absent
  when: ansible_facts.distribution_version != "24.04"

- name: Check for NRPE binary
  ansible.builtin.stat:
    path: /usr/sbin/nrpe
  register: nrpe_bin
  changed_when: false

- name: Install NRPE from source (Debian Only)
  when:
    - ansible_facts.distribution_version != "24.04"
    - not nrpe_bin.stat.exists
  block:
    - name: Install Build tools
      ansible.builtin.apt:
        package:
          - build-essential
          - libssl-dev
          - autoconf
          - automake
          - libtool
    - name: Download NRPE Source
      ansible.builtin.shell: wget https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-4.1.3/nrpe-4.1.3.tar.gz
      args:
        chdir: /tmp
    - name: Unarchive NRPE Source
      ansible.builtin.unarchive:
        src: /tmp/nrpe-4.1.3.tar.gz
        dest: /tmp/
        remote_src: true
    - name: Comile NRPE Source
      ansible.builtin.shell: ./configure --enable-command-args --enable-ssl
      args:
        chdir: "/tmp/nrpe-4.1.3"
    - name: Install NRPE
      ansible.builtin.shell: make "{{ item }}"
      with_items:
        - check_nrpe
        - install
        - install-config
        - install-init
      args:
        chdir: "/tmp/nrpe-4.1.3"

- name: Update NRPE Config
  ansible.builtin.copy:
    src: nagios/nrpe.cfg
    dest: /etc/nagios/nrpe.cfg
  register: nrpe_config

- name: Stop & Disable xinetd
  ansible.builtin.service:
    name: xinetd
    state: stopped
    enabled: false
  become: true
  ignore_errors: true

- name: Copy Scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/lib/nagios/plugins/
    owner: root
    group: root
    mode: 0755
  with_items:
    - nagios/check_cpu.sh
    - nagios/check_mem.sh
    - nagios/check_service.sh
    - nagios/check_docker.sh

- name: Restart NRPE
  ansible.builtin.service:
    name: nagios-nrpe-server
    state: restarted
    enabled: true
  become: true
  when: nrpe_config.changed