- name: Update APT Cache
  apt:
    update_cache: true
  changed_when: false
  ignore_errors: true # This is because of issues with the MPR package repo
- name: Global Utility Installation
  ansible.builtin.apt:
    pkg: "{{ system_packages }}"
  tags: apt
- name: Server Specific Utility Installation
  ansible.builtin.apt:
    pkg: "{{ global_system_server_packages | default('[]')}}"
  when: packages is defined
- name: Figurine Installation
  ansible.builtin.copy:
    src: figurine
    dest: /usr/local/bin/figurine
    mode: '0755'
