- name: Global_System | Packages | Apt Installation
  ansible.builtin.apt:
    name: "{{ system_packages.apt + global_system_server_packages }}"
    update_cache: true
  when: ansible_pkg_mgr == "apt"

- name: Global_System | Packages | Apk Installation
  community.general.apk:
    name: "{{ system_packages.apk + global_system_server_packages }}"
    update_cache: true
  when: ansible_pkg_mgr == "apk"