- name: Global_System | Packages | Update Cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  ignore_errors: true # MPR Downtime Issues

- name: Global_System | Packages | Installation
  ansible.builtin.apt:
    pkg: "{{ system_packages + global_system_server_packages}}"
