- name: SSH - Copy Config File
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    mode: '0644'
  when: inventory_hostname != 'ldnappprd1'
  notify: Restart SSH
- name: SSH - Prevent SSH Host Key Deletion
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: 'ssh_deletekeys:'
    line: 'ssh_deletekeys: false'
    state: present
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['virtualization_type'] == "kvm"
