- name: Global_System | Syslog | Create rsyslog.d directory
  ansible.builtin.file:
    path: /etc/rsyslog.d
    state: directory
    owner: root
    group: root

- name: Global_System | Syslog | Copy Config Files
  ansible.builtin.copy:
    src: "{{ global_system.syslog_config_path }}"
    dest: /etc/
    mode: '0644'
  notify: Restart Syslog

- name: Global_System | Syslog | Configure rsyslog service
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true

- name: Global_System | Syslog | Disable syslog service on Alpine
  ansible.builtin.service:
    name: syslog
    state: stopped
    enabled: false
  when: ansible_os_family == "Alpine"

# - name: Global_System | Syslog | Disable Sudo Logging
#   ansible.builtin.lineinfile:
#     path: /etc/sudoers
#     regexp: '^Defaults.*syslog'
#     line: 'Defaults !syslog'
#     validate: 'visudo -cf %s'

# - name: Global_System | Syslog | Disable Sudo PAM Logging
#   ansible.builtin.replace:
#     path: /etc/pam.d/sudo
#     regexp: '^(session\s+\S+\s+pam_unix\.so(?!.*silent).*)$'
#     replace: '\1 silent'

# - name: Global_System | Syslog | Disable Sudo PAM Logging
#   ansible.builtin.replace:
#     path: /etc/pam.d/sudo
#     regexp: '^(session\s+\S+\s+pam_unix\.so.*)$'
#     replace: '# \1'