- name: Global_System | Syslog | Create rsyslog.d directory
  ansible.builtin.file:
    path: /etc/rsyslog.d
    state: directory
    owner: root
    group: root

- name: Global_System | Syslog | Copy Config Files
  ansible.builtin.copy:
    src: syslog/
    dest: /etc/
    mode: '0644'
  notify: Restart Syslog

- name: Global_System | Syslog | Configure rsyslog service
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true