- name: Configure ssmtp service
  ansible.builtin.lineinfile:
    path: /etc/ssmtp/ssmtp.conf
    create: true
    line: "{{ item }}"
    mode: '0640'
  with_items:
    - root={{ nagios_smtp_username }}
    - server={{ nagios_smtp_host }}
    - UseSTARTTLS=YES
    - FromLineOverride=YES
    - AuthUser={{ nagios_smtp_username }}
    - AuthPass={{ nagios_smtp_password }}
    - mailhub={{ nagios_smtp_host }}:587
    - rewritedomain=epichouse.co.uk
    - hostname={{ nagios_smtp_username }}
  notify: Test SMTP
- name: Configure /etc/ssmtp/revaliases
  ansible.builtin.lineinfile:
    path: /etc/ssmtp/revaliases
    create: true
    line: "root:{{ nagios_smtp_username }}:{{ nagios_smtp_host }}:587"
    mode: '0640'
  notify: Test SMTP
