- name: Download Bitwarden CLI binary
  get_url:
    url: "https://github.com/bitwarden/sdk-sm/releases/download/bws-v2.0.0/bws-x86_64-unknown-linux-gnu-2.0.0.zip"
    dest: /tmp/bws.zip
    mode: '0644'

- name: Unzip Bitwarden CLI
  unarchive:
    src: /tmp/bws.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'