- name: Check if bws is already installed
  stat:
    path: "{{ bws_install_path }}"
  register: bws_stat

- name: Download bws binary
  get_url:
    url: "{{ bws_url }}"
    dest: "{{ bws_install_path }}"
    mode: '0755'
  when: not bws_stat.stat.exists

- name: Verify installation
  command: bws --version
  register: bws_version_output
  changed_when: false