packages:
  - name: samba
    when: storage_server_smb_config_path is not none
  - name: nfs-kernel-server
    when: storage_server_nfs_config_path is not none
  - name: zfsutils-linux
    when: storage_server_zfs is not none
  - name: nfs4-acl-tools
    when: true

firewall_ports:
  - port: 445
    when: storage_server_smb_config_path is not none
  - port: 111
    when: storage_server_nfs_config_path is not none
  - port: 2049
    when: storage_server_nfs_config_path is not none