- name: Bind DNS | Record Config | Dynamic A Record Creation
  community.general.nsupdate:
    server: 127.0.0.1
    record: "{{ item.record }}"
    value: "{{ item.value }}"
    type: A
  with_items: "{{ a_records }}"
  when: a_records != "changeme"
- name: Bind DNS | Record Config | Dynamic PTR Record Creation
  community.general.nsupdate:
    server: 127.0.0.1
    record: "{{ item.record }}"
    value: "{{ item.value }}"
    type: PTR
  with_items: "{{ ptr_records }}"
  when: ptr_records != "changeme"
- name: Bind DNS | Record Config | Dynamic CNAME Record Creation
  community.general.nsupdate:
    server: 127.0.0.1
    record: "{{ item.record }}"
    value: "{{ item.value }}"
    type: CNAME
  with_items: "{{ cname_records }}"
  when: cname_records != "changeme"
- name: Bind DNS | Record Config | Dynamic NS Record Creation
  community.general.nsupdate:
    server: 127.0.0.1
    record: "{{ item | regex_replace('zone', '')}}"
    value: "{{ nameservers }}"
    type: NS
  with_items: "{{ zones.stdout_lines }}"
  when: nameservers != "changeme"
