- name: Bind DNS | Installation
  ansible.builtin.include_tasks: installation.yml
- name: Bind DNS | Global Config
  ansible.builtin.include_tasks: config_global.yml
- name: Bind DNS | Zone Config
  ansible.builtin.include_tasks: config_zones.yml
- name: Bind DNS | Record Config
  ansible.builtin.include_tasks: config_records.yml
  when: zone_type == 'dynamic'
- name: Bind DNS | Testing
  ansible.builtin.include_tasks: testing.yml
