- name: Bind DNS | Installation
  ansible.builtin.include_tasks: installation.yml
  when: include_installation

- name: Bind DNS | Global Config
  ansible.builtin.include_tasks: config_global.yml
  when: include_global_config

- name: Bind DNS | Zone Config
  ansible.builtin.include_tasks: config_zones.yml
  when: include_zone_config

- name: Bind DNS | Record Config
  ansible.builtin.include_tasks: config_records.yml
  when: include_record_config
