username: changeme
github_token: changeme
github_org: changeme
site: changeme
runner_version: "2.321.0"
runner_name: "{{ inventory_hostname }}"
runner_labels: "self-hosted,linux,{{ site }}"
runner_path: "/home/{{ username }}/actions-runner"
