- name: SSMTP Installation
  ansible.builtin.apt:
    pkg:
      - ssmtp

- name: Configure ssmtp service
  ansible.builtin.template:
    dest: /etc/ssmtp/ssmtp.conf
    src: ssmtp.conf.j2
    owner: root
    group: mail
    mode: '0644'

- name: Configure Revaliases
  ansible.builtin.lineinfile:
    path: /etc/ssmtp/revaliases
    owner: root
    group: mail
    mode: '0640'
    create: true
    line: "root:{{ inventory_hostname }}:{{ cron_alerting.smtp_server }}"

- name: Configure Crontab MailFrom
  ansible.builtin.cron:
    env: true
    name: MAILFROM
    job: "{{ cron_alerting.mail_from }}"

- name: Configure Crontab MailTo
  ansible.builtin.cron:
    env: true
    name: MAILTO
    job: "{{ cron_alerting.mail_to }}"
