- name: Cron Management | Create Jobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    day: "{{ item.day }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    job: "{{ item.job }}"
  become: true
  with_items: "{{ cron_jobs }}"

- name: Cron Management | Set MailFrom
  ansible.builtin.cron:
    env: true
    name: MAILFROM
    job: "{{ cron_alerting.mail_from }}"
  when: cron_mail_from is not none

- name: Cron Management | Set MailTo
  ansible.builtin.cron:
    env: true
    name: MAILTO
    job: "{{ cron_alerting.mail_to }}"
  when: cron_mail_to is not none