- name: Cron Management | Create Jobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    day: "{{ item.day | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    job: "{{ item.job }}"
    special_time: "{{ item.special_time | default(omit) }}"
  become: true
  with_items: "{{ cron_management_jobs }}"
  when: cron_management_jobs is not none

- name: Cron Management | Set MailFrom
  ansible.builtin.cron:
    env: true
    name: MAILFROM
    job: "{{ cron_management_mail_from }}"
  when: cron_management_mail_from is not none

- name: Cron Management | Set MailTo
  ansible.builtin.cron:
    env: true
    name: MAILTO
    job: "{{ cron_management_mail_to }}"
  when: cron_management_mail_to is not none