- name: Install Service
  ansible.builtin.command: ./svc.sh install
  args:
    chdir: "{{ runner_path }}"
    creates: "{{ runner_path }}/.service"
  become: true
- name: Start Service
  ansible.builtin.command: ./svc.sh start
  args:
    chdir: "{{ runner_path }}"
  become: true
