- name: Reset SSH Connection
  ansible.builtin.meta: reset_connection
- name: Create runner directory
  ansible.builtin.file:
    path: "{{ runner_path }}"
    state: directory
    mode: '0775'
  changed_when: false
- name: Check for existing archive
  ansible.builtin.stat:
    path: "{{ runner_path }}/vsts-agent-linux-x64-{{ runner_version }}.tar.gz"
  register: runner_archive
- name: Download GitHub Actions Runner
  ansible.builtin.get_url:
    url: "https://vstsagentpackage.azureedge.net/agent/{{ runner_version }}/vsts-agent-linux-x64-{{ runner_version }}.tar.gz"
    dest: "{{ runner_path }}/vsts-agent-linux-x64-{{ runner_version }}.tar.gz"
    mode: '0644'
  when: not runner_archive.stat.exists
  register: download
- name: Extract Archive
  ansible.builtin.unarchive:
    src: "{{ runner_path }}/vsts-agent-linux-x64-{{ runner_version }}.tar.gz"
    dest: "{{ runner_path }}"
    remote_src: true
  when: download.changed

- name: Configure Azure DevOps Agent
  ansible.builtin.command: >
    ./config.sh --url "{{ ado_agent_url }}"
    --agent "{{ ado_agent_name }}"
    --pool "{{ ado_agent_pool }}"
    --auth PAT
    --token "{{ ado_agent_pat }}"
    --nostart
    --acceptTeeEula
    --unattended
  args:
    chdir: "{{ runner_path }}"
    creates: "{{ runner_path }}/.agent"
  notify: Start Service
    - Install Service
    - Start Service
- name: Populate SSH Config
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.ssh/config
    line: "{{ item }}"
    mode: '0755'
    create: true
  become: true
  with_items:
    - "Host *"
    - "   StrictHostKeyChecking no"
