- name: Include unix_users
  ansible.builtin.include_tasks: unix_users.yml
  when: users is defined and enable_user_management

- name: Include ssh_keys
  ansible.builtin.include_tasks: ssh_keys.yml
  when: users is defined and enable_user_management
