- name: Set SSH Private Key
  when: item.ssh_private_key is defined and (item.state | default('present') == 'present')
  ansible.builtin.copy:
    content: "{{ item.ssh_private_key }}"
    dest: "{% if item.username != 'root' %}{{ home_path }}{% endif %}/{{ item.username }}/.ssh/id_rsa"
    mode: '0600'
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
  become: true
  loop_control:
    label: "{{ item.username }}"
  with_items: "{{ users }}"

- name: Remove SSH Private Key if required
  when: not item.ssh_private_key is defined and (item.ssh_manage_keys | default(false))
  ansible.builtin.file:
    path: "{% if item.username != 'root' %}{{ home_path }}{% endif %}/{{ item.username }}/.ssh/id_rsa"
    state: absent
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Set SSH Public Key
  when: item.ssh_public_key is defined and (item.state | default('present') == 'present')
  ansible.builtin.copy:
    content: "{{ item.ssh_public_key }}"
    dest: "{% if item.username != 'root' %}{{ home_path }}{% endif %}/{{ item.username }}/.ssh/id_rsa.pub"
    mode: '0644'
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Remove SSH Public Key if required
  when: not item.ssh_public_key is defined and (item.ssh_manage_keys | default(false))
  ansible.builtin.file:
    path: "{% if item.username != 'root' %}{{ home_path }}{% endif %}/{{ item.username }}/.ssh/id_rsa.pub"
    state: absent
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Populate SSH Config file
  when: item.ssh_config is defined and (item.state | default('present') == 'present')
  ansible.builtin.copy:
    content: "{{ item.ssh_config }}"
    dest: "{% if item.username != 'root' %}{{ home_path }}{% endif %}/{{ item.username }}/.ssh/config"
    mode: '0600'
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Install authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
    exclusive: "{{ item.0.ssh_manage_keys | default(false) }}"
  when:  item.state | default('present') == 'present'
  loop: "{{ users | subelements('ssh_authorized_keys', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.username }}"

- name: Remove authorized_keys file if required
  when: not item.ssh_authorized_keys is defined and (item.ssh_manage_keys | default(false))
  ansible.builtin.file:
    path: "{% if item.username != 'root' %}{{ home_path }}{% endif %}/{{ item.username }}/.ssh/authorized_keys"
    state: absent
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"