- name: Create Unix Group
  when: item.create_group | default(true)
  ansible.builtin.group:
    name: "{{ item.username }}"
    state: present
    gid: "{{ item.gid | default(item.uid) }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Create/Modify Unix User
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.username }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell | default('/bin/bash')}}"
    group: "{{ item.group | default(item.username) }}"
    password: "{{ (item.password | password_hash('sha512')) | default('!') }}"
    append: "{{ item.append | default(true) }}"
    groups: users
    state: "{{ item.state | default('present')}}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"
  changed_when: false

- name: Add Unix User to users group
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: users
    append: true
    state: "{{ item.state | default('present')}}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Configure sudoers
  ansible.builtin.template:
    dest: "/etc/sudoers.d/{{ item.username }}"
    src: sudoers.j2
    mode: 0644
    state: "{{ 'absent' if item.sudoers is not defined else item.state | default('present') }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Create Home Directory Dirs
  ansible.builtin.file:
    path: "{% if item.0.username != 'root' %}{{ home_path }}{% endif %}/{{ item.0.username }}{{ item.1.dir }}"
    mode: "{{ item.1.mode }}"
    owner: "{{ item.0.username }}"
    group: "{{ item.0.username }}"
    state: "{{ item.0.state | default('directory') }}"
  loop: "{{ users | product(static_dirs) | list }}"
  loop_control:
    label: "{{ item.0.username }} - {{ item.1 }}"

- name: Copy Home Directory Files
  ansible.builtin.copy:
    src: "{{ item.1.src }}"
    dest: "{% if item.0.username != 'root' %}{{ home_path }}{% endif %}/{{ item.0.username }}/{{ item.1.dest | default() }}"
    mode: 0644
    owner: "{{ item.0.username }}"
    group: "{{ item.0.username }}"
  when: "{{ item.0.state | default('present') == 'present'}}"
  loop: "{{ users | subelements('home_dir_files', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.username }} - {{ item.1.src }}"