- name: Create Unix Group
  when: item.create_group | default(true)
  ansible.builtin.group:
    name: "{{ item.username }}"
    state: present
    gid: "{{ item.gid | default(item.uid) }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Create/Modify Unix User
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.username }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell | default('/bin/bash')}}"
    group: "{{ item.group | default(item.username) }}"
    password: "{{ (item.password | password_hash('sha512')) | default('!') }}"
    append: "{{ item.append | default(true) }}"
    groups: users
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"
  changed_when: false

- name: Add Unix User to users group
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: users
    append: true
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Allow sudo without password
  when: item.allow_sudo | default(false)
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ item.username }}"
    line: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL"
    create: true
    mode: 0644
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Remove no longer required sudoers file
  when: not (item.allow_sudo | default(false))
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ item.username }}"
    state: absent
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Copy Home Directory Files
  when: item.0.home_dir_files is defined
  ansible.builtin.copy:
    content: "{{ item.1.source }}"
    dest: "{% if item.0.username != 'root' %}/home{% endif %}/{{ item.0.username }}/{{ item.1.dest }}"
    mode: 0644
    owner: "{{ item.0.username }}"
    group: "{{ item.0.username }}"
  with_items: "{{ users }}"
  loop: "{{ users | subelements('home_dir_files', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.username }}{{ item.1.source }}"