- name: Unix Groups | Create Groups
  when: item.create_group | default(true)
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    gid: "{{ item.gid }}"
  with_items: "{{ groups }}"
  loop_control:
    label: "{{ item.name }}"

- name: Unix Groups | Add Members to groups
  ansible.builtin.user:
    name: "{{ item.1.name }}"
    groups: "{{ item.0.name }}"
    append: true
  become: true
  loop: "{{ groups | subelements('members', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.name }} | {{ item.1.name | default('') }}"