- name: Use Password Manager
  ansible.builtin.include_tasks: pwd_mgr.yml
  when: mode == "pwd_mgr"
- name: Use Secrets Manager
  ansible.builtin.include_tasks: secrets_mgr.yml
  when: mode == "secrets_mgr"