- name: Check for home dir git Repository
  ansible.builtin.stat:
    path: ~/.git
  register: home_git
- name: Configure Home Directory Git Repository
  when: not home_git.stat.exists
  block:
    - name: Initialise Repo
      ansible.builtin.shell: git init -b main
      args:
        chdir: "/home/{{ home.username }}"
    - name: Add Remote
      ansible.builtin.shell: "git remote add origin {{ home.repository }}"
      args:
        chdir: "/home/{{ home.username }}"
    - name: Delete files that will conflict
      ansible.builtin.file:
        path: "~/{{ item }}"
        state: absent
      with_items:
        - .bashrc
        - .profile
        - .config/neofetch/config.conf
    - name: Pull Remote Main Branch 
      ansible.builtin.shell: git pull origin main
      args:
        chdir: "/home/{{ home.username }}"
    - name: Set Upstream Branch
      shell: git branch --set-upstream-to=origin/main
      args:
        chdir: "/home/{{ home.username }}"
    - name: Pull to confirm working
      shell: git pull
      args:
        chdir: "/home/{{ home.username }}"
