- name: AWS Credentials | Create Config Directory
  ansible.builtin.file:
    path: "/home/{{ username }}/.aws"
    state: directory
    mode: '0700'
    owner: "{{ username }}"
    group: "{{ username }}"
  become: true
- name: AWS Credentials | Create Credentials File
  ansible.builtin.template:
    src: aws_credentials.j2
    dest: "/home/{{ username }}/.aws/credentials"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0600'
  become: true
