- name: Main | Ensure necessary dependencies are installed
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present
    update_cache: true
  become: true
- name: Main | Create runner directory
  ansible.builtin.file:
    path: "{{ runner_path }}"
    state: directory
    mode: '0775'
    owner: "{{ username }}"
    group: "{{ username }}"
  changed_when: false
  become: true
- name: Main | Download Gitea Actions Runner
  ansible.builtin.get_url:
    url: "{{ runner_url }}"
    dest: "{{ runner_path }}/act_runner"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  become: true

- name: Main | Configure Gitea Actions Runner
  ansible.builtin.command: >
    ./act_runner register
    --no-interactive
    --instance {{ gitea_instance }}
    --token {{ gitea_token }}
    --name {{ runner_name }}
    --labels {{ runner_labels }}
  args:
    chdir: "{{ runner_path }}"
    creates: "{{ runner_path }}/.runner"
  become: true

- name: Main | Configure .runner permissions
  ansible.builtin.file:
    path: "{{ runner_path }}/.runner"
    state: file
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"
  become: true

- name: Main | Create Gitea Actions Runner service
  ansible.builtin.template:
    src: act_runner.service.j2
    dest: /etc/systemd/system/act_runner.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Main | Ensure Service is started and enabled
  ansible.builtin.service:
    name: act_runner
    state: started
    enabled: true
  become: true

- name: Main | Populate SSH Config
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.ssh/config
    line: "{{ item }}"
    mode: '0755'
    create: true
  become: true
  with_items:
    - "Host *"
    - "   StrictHostKeyChecking no"

- name: Main | Install AZ CLI
  ansible.builtin.include_tasks: az_cli.yml
- name: Main | Install Ansible
  ansible.builtin.include_tasks: ansible.yml
- name: Main | Install Terraform
  ansible.builtin.include_tasks: terraform.yml
- name: Main | Install Docker
  ansible.builtin.include_tasks: docker.yml
- name: Main | Configure AWS S3 Credentials
  ansible.builtin.include_tasks: aws_credentials.yml
