- name: Main | Install Gitea Runner
  ansible.builtin.include_tasks: agent/configure.yml
- name: Main | Execute Misc Tasks
  ansible.builtin.include_tasks: agent/misc.yml
- name: Main | Install AZ CLI
  ansible.builtin.include_tasks: utils/az_cli.yml
- name: Main | Install Ansible
  ansible.builtin.include_tasks: utils/ansible.yml
- name: Main | Install Terraform
  ansible.builtin.include_tasks: utils/terraform.yml
- name: Main | Install Docker
  ansible.builtin.include_tasks: utils/docker.yml
