# File is included via pools.yml
- name: Storage Server | ZFS | Create Dataset
  community.general.zfs:
    name: "{{ pool_item.key }}/{{ item.key }}"
    state: "{{ item.value.state | default('present') }}"
    extra_zfs_properties: "{{ item.value.extra_zfs_properties | default({}) }}"
  loop: "{{ pool_item.value.datasets | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  become: true

- name: Storage Server | ZFS | Configure ACLs for Dataset
  include_tasks: zfs/rbac.yml
  loop: "{{ pool_item.value.datasets | dict2items }}"
  when: dataset_item.permissions is defined
  loop_control:
    loop_var: dataset_item
    label: "{{ pool_item.key }}/{{ dataset_item.key }}"