- name: Storage Server | ZFS | Create Pools
  community.general.zpool:
    name: "{{ item.key }}"
    vdevs: "{{ item.value.vdevs }}"
    altroot: "{{ item.value.altroot | default(omit) }}"
    disable_new_features: "{{ item.value.disable_new_features | default(false) }}"
    filesystem_properties: "{{ item.value.filesystem_properties | default({}) }}"
    force: "{{ item.value.force | default(false) }}"
    mountpoint: "{{ item.value.mountpoint | default('/mnt/' + item.key) }}"
    pool_properties: "{{ item.value.pool_properties | default({}) }}"
    state: "{{ item.value.state | default('present') }}"
    temp_name: "{{ item.value.temp_name | default(omit) }}"
  when:
    - storage_server_zfs.pools is defined
    - item.value.vdevs is defined
  loop: "{{ storage_server_zfs.pools | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  become: true

- name: Storage Server | ZFS | Create Datasets
  include_tasks: zfs/datasets.yml
  loop: "{{ storage_server_zfs.pools | dict2items }}"
  loop_control:
    loop_var: pool_item
    label: "{{ pool_item.key }}"
