# File is included via datasets.yml
- name: Storage Server | ZFS | Set Unix Permissions
  ansible.builtin.file:
    path: "{{ dataset_item.value.extra_zfs_properties.mountpoint | default('/mnt/' + pool_item.key + '/' + dataset_item.key) }}"
    mode: "{{ dataset_item.value.mode | default('0770') }}"
    owner: "{{ dataset_item.value.owner | default('root') }}"
    group: "{{ dataset_item.value.group | default('root') }}"
  become: true
  when:
    - not item.extra_zfs_properties.mountpoint is defined

- name: Storage Server | ZFS | Remove implicit ACL entries
  ansible.builtin.command:
    cmd: >-
      setfacl -R -x {{ item.etype | default('group') | first }}:{{ item.entity }}
      {{ dataset_item.value.extra_zfs_properties.mountpoint | default('/mnt/' + pool_item.key + '/' + dataset_item.key) }}
  loop: "{{ dataset_item.value.permissions | default([]) }}"
  loop_control:
    label: "{{ dataset_item.key }} | {{ item.entity }}"
  when: item.state | default('present') == 'absent'
  become: true
  changed_when: true

- name: Storage Server | ZFS | Remove default ACL entries
  ansible.builtin.command:
    cmd: >-
      setfacl -R -x d:{{ item.etype | default('group') | first }}:{{ item.entity }}
      {{ dataset_item.value.extra_zfs_properties.mountpoint | default('/mnt/' + pool_item.key + '/' + dataset_item.key) }}
  loop: "{{ dataset_item.value.permissions | default([]) }}"
  loop_control:
    label: "{{ dataset_item.key }} | {{ item.entity }}"
  when: item.state | default('present') == 'absent'
  become: true
  changed_when: true

- name: Storage Server | ZFS | Configure implicit ACL
  ansible.posix.acl:
    path: "{{ dataset_item.value.extra_zfs_properties.mountpoint | default('/mnt/' + pool_item.key + '/' + dataset_item.key) }}"
    entity: "{{ item.entity }}"
    etype: "{{ item.etype | default('group') }}"
    permissions: "{{ item.permissions | default(omit) }}"
    default: false
    state: "{{ item.state | default('present') }}"
    recursive: "{{ item.recursive | default(true) }}"
  loop: "{{ dataset_item.value.permissions | default([]) }}"
  loop_control:
    label: "{{ dataset_item.key }} | {{ item.entity }}"
  become: true
  when:
    - item.entity is defined

- name: Storage Server | ZFS | Configure default ACL
  ansible.posix.acl:
    path: "{{ dataset_item.value.extra_zfs_properties.mountpoint | default('/mnt/' + pool_item.key + '/' + dataset_item.key) }}"
    entity: "{{ item.entity }}"
    etype: "{{ item.etype | default('group') }}"
    permissions: "{{ item.permissions | default(omit) }}"
    default: true
    state: "{{ item.state | default('present') }}"
    recursive: "{{ item.recursive | default(true) }}"
  loop: "{{ dataset_item.value.permissions | default([]) }}"
  loop_control:
    label: "{{ dataset_item.key }} | {{ item.entity }}"
  when:
    - item.default | default(true) | bool
    - item.entity is defined
  become: true