system_packages:
  - nano
  - htop
  - git
  - net-tools
  - dnsutils
  - rsync
  - tmux
  - rsyslog
  - unzip
  - ca-certificates
  - curl
  - gnupg
  - fio
  - inxi
  - smartmontools
  - acl
  - xclip
  - btop
  - gpg
  - cron
  - nfs-common
  - just
