system_packages:
  apt:
    - sudo
    - nano
    - htop
    - git
    - net-tools
    - dnsutils
    - rsync
    - tmux
    - rsyslog
    - unzip
    - ca-certificates
    - curl
    - gnupg
    - fio
    - inxi
    - smartmontools
    - acl
    - xclip
    - btop
    - gpg
    - cron
    - nfs-common
    - just
    - nagios-plugins
  apk:
    # - sudo - needs community repo??? tf
    - nano
    - htop
    - git
    - net-tools
    - rsync
    - tmux
    - rsyslog
    - unzip
    - ca-certificates
    - curl
    - gnupg
    - smartmontools
    - acl
    - gpg
    # - cron - not in main repo
    # - just - not in main repo
    - nagios-plugins
