system_packages:
  apt:
    - sudo
    - nano
    - htop
    - git
    - net-tools
    - dnsutils
    - rsync
    - tmux
    - rsyslog
    - unzip
    - ca-certificates
    - curl
    - gnupg
    - fio
    - inxi
    - smartmontools
    - acl
    - xclip
    - btop
    - gpg
    - cron
    - nfs-common
    - just
    - nagios-plugins
    - qemu-guest-agent
  apk_repositories:
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
  apk:
    - bash
    - sudo
    - nano
    - htop
    - git
    - net-tools
    - rsync
    - tmux
    - rsyslog
    - unzip
    - ca-certificates
    - curl
    - gnupg
    - smartmontools
    - acl
    - gpg
    - just
    - nagios-plugins
    - tzdata
    - qemu-guest-agent
    - tar
    - shadow