- name: SMTP Configuration
  lucasheld.uptime_kuma.notification:
    api_url: "{{ config.api_url }}"
    api_token: "{{ api_token }}"
    name: SMTP
    type: smtp
    smtpHost: "{{ config.smtp_host }}"
    smtpFrom: "{{ config.smtp_from }}"
    smtpTo: "{{ config.smtp_to }}"
    smtpUsername: "{{ config.smtp_username }}"
    smtpPassword: "{{ config.smtp_password }}"
    smtpPort: 465
    smtpSecure: 'true'
    state: present
  when: config.enable_smtp
# TODO: Make this dynamic