- name: Test Configuration
  ansible.builtin.command: nginx -t
  listen: Reload Web
  notifty: Reload Web Service

- name: Reload Web Service
  ansible.builtin.service:
    name: nginx
    state: reloaded

