- name: Check for NRPE binary
  ansible.builtin.stat:
    path: /usr/local/nagios/bin/nrpe
  register: nrpe_bin
  changed_when: false

- name: Install NRPE from source
  when:
    - not nrpe_bin.stat.exists
  block:
    - name: Install Build tools
      ansible.builtin.apt:
        package:
          - build-essential
          - libssl-dev
          - autoconf
          - automake
          - libtool
    - name: Download NRPE Source
      ansible.builtin.shell: wget https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-4.1.3/nrpe-4.1.3.tar.gz
      args:
        chdir: /tmp
    - name: Unarchive NRPE Source
      ansible.builtin.unarchive:
        src: /tmp/nrpe-4.1.3.tar.gz
        dest: /tmp/
        remote_src: true
    - name: Comile NRPE Source
      ansible.builtin.shell: ./configure --enable-command-args --enable-ssl
      args:
        chdir: "/tmp/nrpe-4.1.3"
    - name: Install NRPE
      ansible.builtin.shell: make "{{ item }}"
      with_items:
        - all
        - install
        - install-groups-users
        - install-plugin
        - install-config
        - install-init
      args:
        chdir: "/tmp/nrpe-4.1.3"

- name: Copy Scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/lib/nagios/plugins/
    owner: root
    group: root
    mode: 0755
  with_items:
    - check_cpu.sh
    - check_mem.sh
    - check_service.sh
    - check_docker.sh

- name: Stop & Disable xinetd
  ansible.builtin.service:
    name: xinetd
    state: stopped
    enabled: false
  become: true
  ignore_errors: true