- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true
- name: Restart Syslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  become: true
