- name: Restart SSH
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  become: true
  ignore_errors: true
  with_items:
    - ssh
    - sshd
- name: Restart Syslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  become: true
- name: Restart Cloud Init
  ansible.builtin.service:
    name: cloud-init
    state: restarted
  become: true
