- name: Restart SSH Service
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  become: true
  ignore_errors: true
  with_items:
    - ssh
    - sshd
- name: Restart Syslog Service
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  become: true
