- name: Install Dependancies on local machine
  ansible.builtin.apt:
    name: python3-passlib
    state: present
  become: true
  delegate_to: localhost
# - name: Install Sudo
#   become: true
#   ansible.builtin.apt:
#     pkg: sudo
- name: Create Group
  ansible.builtin.group:
    name: "{{ username }}"
    state: present
    gid: "{{ gid }}"
  become: true
- name: Create Group
  ansible.builtin.user:
    name: "{{ username }}"
    comment: "{{ username }}"
    uid: "{{ uid }}"
    shell: /bin/bash
    group: "{{ username }}"
    groups: users
    password: "{{ password | password_hash('sha512') }}"
    append: true
  changed_when: false
  become: true
- name: Add to Users Group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: users
    append: true
  become: true
- name: Add to Sudo Group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: sudo
    append: true
  become: true
- name: Allow passwordless sudo
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ username }}"
    line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
    create: true
    mode: '0644'
  become: true
- name: Create .ssh directory
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    mode: '0755'
  become: true
- name: SSH - Set Private Key
  ansible.builtin.copy: # TODO: Make this dynamic
    content: "{{ ssh_private_key }}"
    dest: "/home/{{ username }}/.ssh/id_rsa"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
  become: true
- name: SSH - Set Public Key
  ansible.builtin.copy: # TODO: Make this dynamic
    content: "{{ ssh_public_key }}"
    dest: "/home/{{ username }}/.ssh/{{ item }}"
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - id_rsa.pub
    - authorized_keys
  become: true
- name: Reset SSH Connection
  ansible.builtin.meta: reset_connection