docker_host_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_host_applications: "{{ docker_compose_projects | map(attribute='name') | list }}"