- name: Global_User | HTOPRC | Create Directory
  ansible.builtin.file:
    path: "/home/{{ global_user_username }}/.config/htop"
    state: directory
    mode: '0755'
    owner: "{{ global_user_username }}"
    group: "{{ global_user_username }}"
- name: Global_User | HTOPRC | Copy Virtual Machine File
  ansible.builtin.copy:
    src: htoprc-virtual
    dest: "/home/{{ global_user_username }}/.config/htop/htoprc"
    mode: '0755'
    owner: "{{ global_user_username }}"
    group: "{{ global_user_username }}"
  when: ansible_facts['virtualization_role'] == "guest"
- name: Global_User | HTOPRC | Copy Physical Machine File
  ansible.builtin.copy:
    src: htoprc-physical
    dest: "/home/{{ global_user_username }}/.config/htop/htoprc"
    force: true
    mode: '0755'
    owner: "{{ global_user_username }}"
    group: "{{ global_user_username }}"
  when: ansible_facts['virtualization_role'] == "host"
