- name: HTOPRC - Create Directory
  ansible.builtin.file:
    path: ~/.config/htop
    state: directory
    mode: '0755'
- name: HTOPRC - Copy Virtual Machine File
  ansible.builtin.copy:
    src: htoprc-virtual
    dest: ~/.config/htop/htoprc
    mode: '0755'
  when: ansible_facts['virtualization_role'] == "guest"
- name: HTOPRC - Copy Physical Machine File
  ansible.builtin.copy:
    src: htoprc-physical
    dest: ~/.config/htop/htoprc
    force: true
    mode: '0755'
  when: ansible_facts['virtualization_role'] == "host"
