- name: Global_User | Include bashrc Tasks
  ansible.builtin.include_tasks: bashrc.yml
- name: Global_User | Include htoprc Tasks
  ansible.builtin.include_tasks: htoprc.yml
- name: Global_User | Include ssh Tasks
  ansible.builtin.include_tasks: ssh.yml
- name: Global_User | Include misc Tasks
  ansible.builtin.include_tasks: misc.yml
