- name: Global_User | Misc | Ensure Directory Exists
  ansible.builtin.file:
    path: "/home/{{ global_user_username }}/git"
    mode: '0755'
    state: directory
    owner: "{{ global_user_username }}"
    group: "{{ global_user_username }}"
