- name: Global_User | SSH | Set Public Key
  ansible.builtin.copy:
    content: "{{ global_user_public_ssh_key }}"
    dest: "{{ item.dir }}/.ssh/id_rsa.pub"
    mode: '0644'
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  with_items:
    - user: "{{ global_user_username }}"
      group: "{{ global_user_group }}"
      dir: "{{ global_user_home_directory }}"
    - user: "root"
      group: "root"
      dir: "/root"

- name: Global_User | SSH | Set authorized_keys
  ansible.builtin.copy:
    content: "{{ global_user_public_ssh_key }}"
    dest: "{{ item.dir }}/.ssh/authorized_keys"
    mode: '0644'
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  with_items:
    - user: "{{ global_user_username }}"
      group: "{{ global_user_group }}"
      dir: "{{ global_user_home_directory }}"
    - user: "root"
      group: "root"
      dir: "/root"

- name: Global_User | SSH | Set Private Key
  ansible.builtin.copy:
    content: "{{ global_user_private_ssh_key }}"
    dest: "{{ item.dir }}/.ssh/id_rsa"
    mode: '0600'
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  with_items:
    - user: "{{ global_user_username }}"
      group: "{{ global_user_group }}"
      dir: "{{ global_user_home_directory }}"
    - user: "root"
      group: "root"
      dir: "/root"

- name: Global_User | SSH | Populate Config (user)
  ansible.builtin.lineinfile:
    path: "{{ item.dir }}/.ssh/config"
    line: "Host * StrictHostKeyChecking no"
    mode: '0755'
    create: true
  with_items:
    - user: "{{ global_user_username }}"
      dir: "{{ global_user_home_directory }}"
    - user: "root"
      dir: "/root"
