nagios_agent_packages:
  - build-essential
  - libssl-dev
  - autoconf
  - automake
  - libtool

nrpe_install_media: https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-4.1.3/nrpe-4.1.3.tar.gz