- name: Reload Docker
  ansible.builtin.systemd:
    name: docker
    state: reloaded

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true