default:
	just --list

# List current dir using tree
[no-cd]
ls:
	tree . -L 1
# Set Power Mode to High Performance
phigh:
	powershell.exe 'powercfg /setactive SCHEME_MIN'
# Set Power Mode to Balanced
pmid:
	powershell.exe 'powercfg /setactive SCHEME_BALANCED'
# Set Power Mode to Power Saver
plow:
	powershell.exe 'powercfg /setactive SCHEME_MAX'
# Get Power Mode
pget:
	powershell.exe 'powercfg /getactivescheme' && echo ""

#Steam Locomotive!!!
train:
	sl

# Run WSL provisioning script
[no-cd]
wsl:
	/home/$(whoami)/git/epichouse/client-config/setup-wsl.sh

# Run Git provisioning script
[no-cd]
git:
	/home/$(whoami)/git/epichouse/client-config/setup-git.sh

[no-cd]
gc:
	git add . && git commit -a -m $MSG

[no-cd]
gp:
	git push