- name: Act Configuration | Install dependancies
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present
    update_cache: true
- name: Act Configuration | Create runner directory
  ansible.builtin.file:
    path: "{{ github_actions_runner_path }}"
    state: directory
    mode: '0775'
    owner: "{{ github_actions_username }}"
    group: "{{ github_actions_username }}"

- name: Check for existing archive
  ansible.builtin.stat:
    path: "{{ github_actions_runner_path }}/actions-runner-linux-x64-{{ runner_version }}.tar.gz"
  register: runner_archive
- name: Download GitHub Actions Runner
  ansible.builtin.get_url:
    url: "https://github.com/actions/runner/releases/download/v{{ runner_version }}/actions-runner-linux-x64-{{ runner_version }}.tar.gz"
    dest: "{{ github_actions_runner_path }}/actions-runner-linux-x64-{{ runner_version }}.tar.gz"
    mode: '0644'
  when: not runner_archive.stat.exists
  become: true
  become_user: "{{ github_actions_username }}"
- name: Extract Archive
  ansible.builtin.unarchive:
    src: "{{ github_actions_runner_path }}/actions-runner-linux-x64-{{ runner_version }}.tar.gz"
    dest: "{{ github_actions_runner_path }}"
    remote_src: true
  when: not runner_archive.stat.exists
  become: true
  become_user: "{{ github_actions_username }}"

- name: Configure GitHub Actions Runner
  ansible.builtin.command: "./config.sh --url https://github.com/{{ github_actions_org }} --token {{ github_token }} --name {{ github_actions_runner_name }} --labels {{ runner_labels }} --runnergroup Default --work _work"
  args:
    chdir: "{{ github_actions_runner_path }}"
    creates: "{{ github_actions_runner_path }}/.runner"
  register: runner_conf
  become: true
  become_user: "{{ github_actions_username }}"

- name: Install Service
  ansible.builtin.command: ./svc.sh install
  args:
    chdir: "{{ github_actions_runner_path }}"
    creates: "{{ github_actions_runner_path }}/.service"
  become: true
  become_user: "{{ github_actions_username }}"
  when: runner_conf.changed
- name: Start Service
  ansible.builtin.service:
    name: actions.runner.{{ github_actions_org | replace('/', '.') }}.{{ github_actions_runner_name }}.service
    state: started
    enabled: true
  become: true