- name: APT Packages | Update Cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  ignore_errors: true # This is because of issues with the MPR package repo

- name: APT Packages | Global Utility Installation
  ansible.builtin.apt:
    pkg: "{{ system_packages.global + system_packages.apt }}"

- name: APT Packages | Server Specific Utility Installation
  ansible.builtin.apt:
    pkg: "{{ global_system_server_packages | default('[]') }}"
  when: global_system_server_packages != []

- name: APT Packages | CheckMK Agent Installation
  when: global_system_checkmk_install
  block:
    - name: CheckMK Agent | Copy Installation Media
      ansible.builtin.copy:
        src: check-mk-agent_2.3.0p30-1_all.deb
        dest: /tmp
        mode: '0644'
        owner: root
        group: root
    - name: CheckMK Agent | Install Agent
      ansible.builtin.apt:
        deb: /tmp/check-mk-agent_2.3.0p30-1_all.deb
        disable_gpg_check: true
        state: present
