storage_server_smb_config_path: null
storage_server_nfs_config_path: null
storage_server_zfs: null
storage_server_permissions: null
storage_server_filesystem: null
storage_server_rclone_config_path: null

enable_permissions: true
enable_installation: true
enable_firewall_config: true
enable_samba: true
enable_nfs: true
enable_zfs_config: true
enable_filesystem_tasks: true
enable_rclone: true
enable_builtin_cron_jobs: true