storage_server_smb_config_path: # Path to smb.conf in local deployment
storage_server_nfs_config_path:  # Path to nfs exports in local deployment
storage_server_zfs: # ZFS config, emit for zfs installation to be skipped
  sanoid_config_path: # Path to sanoid config file, sanoid install skipped if omitted
  zed:
    email: zfs@example.com
    verbose: 1
    notify_interval_secs: 3600
    notify_verbose: 0
  pools:
    - name: # Pool Name
      vdevs: # Dictionary of vdevs
        - type: mirror
          disks:
            - /dev/sda
            - /dev/sdb
      altroot: # Alternate root for mounting filesystems.
      disable_new_features: # disable new ZFS feature flags when creating
      filesystem_properties: # Dictionary of ZFS filesystem properties to set on the root dataset
      force: # Force Operations
      mountpoint: # Root dataset mount point
      pool_properties: # Dictionary of ZFS pool properties to set
      state: # set to absent to remove
      temp_name: # Temporary name used during pool creation.
  datasets:
    - name: # dataset name
      extra_zfs_properties: # All ZFS options
      state: # set to absent to delete dataset
      acl: # omit for no ACL (inherited only)
        entity: # entity (user/group)
        etype: # entity type
        permissions: # Leave blank for removal
        default: # Create default ACL (default = true)
        state: # set to absent for ACL removal (default = present)



filesystem:
  directories:
    - name: /etc/directory
      mode: '0770' # This option is default
      owner: root # This option is default
      group: users # This option is default
  copy_files:
    - src: ../example_path # Local git path
      dest: ../example_path # Remote destination
      mode: '0770' # This option is default
      owner: root # This option is default
      group: users # This option is default