storage_server_smb_config_path: # Path to smb.conf in local deployment
storage_server_nfs_config_path:  # Path to nfs exports in local deployment
storage_server_rclone_config_path: # Path to rclone config in local deployment (J2 Template)
storage_server_rclone_config_dest: # Custom destination for rclone config ('/root/.config/rclone/rclone.conf' by default)
storage_server_zfs: # ZFS config, emit for zfs installation to be skipped
  sanoid_config_path: # Path to sanoid config file, sanoid install skipped if omitted
  sanoid_enable_timer: # Enable systemd timer for sanoid (disabled by default)
  zed:
    email: zfs@example.com
    verbose: 1
    notify_interval_secs: 3600
    notify_verbose: 0
  pools:
    - name: data # Pool name
      vdevs: # Dictionary of vdevs
        - type: mirror
          disks:
            - /dev/sda
            - /dev/sdb
      altroot: # Alternate root for mounting filesystems.
      disable_new_features: # disable new ZFS feature flags when creating
      filesystem_properties: # Dictionary of ZFS filesystem properties to set on the root dataset
      force: # Force Operations
      mountpoint: # Root dataset mount point (default is /mnt/{pool name})
      pool_properties: # Dictionary of ZFS pool properties to set
      state: # set to absent to remove
      temp_name: # Temporary name used during pool creation.
  datasets:
    - name: test # dataset name (ommiting pool name)
      extra_zfs_properties: # All ZFS options
      state: # set to absent to delete dataset
      acl: # Optional dataset-scoped acl, applied to the dataset mount point, idempotent - ACL's not listed will be removed
        - u:userhere:rwx
        - g:yourgroup:rx
      unix_permissions:
        - mode: # Mode to set if required (default 770)
          owner: # Owner to set if required (default root)
          group: # Group to set if required (default root)
          ignore: # Do not modify unix permissions (default false)

storage_server_permissions:
  - path: # Path to apply unix permissions or acl to
    mode: # Mode to set if required
    owner: # Owner to set if required
    group: # Group to set if required
    entity: # ACL entity if required
    etype: # ACL entity type if required (default=group)
    permissions: # ACL permissions if required
    default: # ACL as default (default=true)
    state: # default is present

storage_server_filesystem:
  directories:
    - name: /etc/directory
      mode: '0770' # This option is default
      owner: root # This option is default
      group: users # This option is default
  copy_files:
    - src: ../example_path # Local git path
      dest: ../example_path # Remote destination
      mode: '0770' # This option is default
      owner: root # This option is default
      group: users # This option is default