cron_alerting:
  smtp_server:
  smtp_user:
  smtp_password:
  smtp_domain:
  mail_to:
  mail_from:

cron_jobs:
  - name: example job
    day: '*'
    hour: '23'
    minute: '30'
    job: "/bin/bash /srv/scripts/script.sh"
