- name: Configuration | Get Required Projects
  ansible.builtin.shell: ls "../servers/{{ docker.host }}/compose" | sed 's/\.[^.]*$//' | sed 's/\.[^.]*$//'
  register: applications
  delegate_to: localhost
  become: true
  changed_when: false
- name: applications
  ansible.builtin.debug:
    msg: "{{applications}}"
- name: Configuration | Ensure data directories exist for required projects
  ansible.builtin.file:
    path: "{{ docker.paths.volumes }}/{{ item }}"
    owner: root
    group: docker
    mode: '0770'
    state: directory
  become: true
  with_items: "{{ applications.stdout_lines }}"
- name: Configuration | Ensure app directories exist for required projects
  ansible.builtin.file:
    path: "{{ docker.paths.apps }}/{{ item }}"
    owner: root
    group: docker
    mode: '0770'
    state: directory
  become: true
  with_items: "{{ applications.stdout_lines }}"
- name: Configuration | Generate compose files from Jinja templates
  ansible.builtin.template:
    src: "../servers/{{ docker.host }}/compose/{{ item }}.yml.j2"
    dest: "{{ docker.paths.apps }}/{{ item }}/compose.yaml"
    owner: root
    group: docker
    mode: '0770'
  with_items: "{{ applications.stdout_lines }}"
  become: true
- name: Configuration | Ensure all deployed compose projects are running
  community.docker.docker_compose_v2:
    project_name: "{{ item }}"
    project_src: "{{ docker.paths.apps }}/{{ item }}"
    remove_orphans: true
    state: present
  tags: docker
  become: true
  with_items: "{{ applications.stdout_lines }}"
- name: Configuration | Get running Compose projects
  ansible.builtin.shell: "docker compose ls -q"
  register: currentapplications
  become: true
  changed_when: false
- name: Configuration | Stop non-required projects
  ansible.builtin.shell: "docker compose -p {{ item }} down"
  with_items: "{{ currentapplications.stdout_lines | difference(applications.stdout_lines) }}"
  become: true
- name: Configuration | Remove non-required projects
  ansible.builtin.file:
    path: "{{ docker.paths.apps }}/{{ item }}"
    state: absent
  become: true
  with_items: "{{ currentapplications.stdout_lines | difference(applications.stdout_lines) }}"
