- name: Docker | Configuration | Get Required Projects
  ansible.builtin.shell: ls "{{ docker_config_path }}" | sed 's/\.[^.]*$//' | sed 's/\.[^.]*$//'
  register: applications
  delegate_to: localhost
  become: true
  changed_when: false

- name: Docker | Configuration | Create Directories
  ansible.builtin.file:
    path: "{{ docker.paths.volumes }}/{{ item }}"
    owner: root
    group: docker
    mode: '0770'
    state: directory
  become: true
  with_items: "{{ docker_dirs | product(applications.stdout_lines) | map('join', '/') | list }}"
  vars:
    docker_dirs:
      - "{{ docker.paths.volumes }}"
      - "{{ docker.paths.apps }}"


- name: Docker | Configuration | Generate Compose Files
  ansible.builtin.template:
    src: "{{ docker_config_path }}/{{ item }}.yml.j2"
    dest: "{{ docker.paths.apps }}/{{ item }}/compose.yaml"
    owner: root
    group: docker
    mode: '0770'
  with_items: "{{ applications.stdout_lines }}"
  become: true
  register: compose

- name: Docker | Configuration | Start Compose Projects
  community.docker.docker_compose_v2:
    project_name: "{{ item.item }}"
    project_src: "{{ docker.paths.apps }}/{{ item.item }}"
    remove_orphans: true
    build: never
    state: present
  tags: docker
  become: true
  with_items: "{{ compose.results }}"
#  when: item.changed
  loop_control:
    label: "{{ item.item }}"


- name: Docker | Configuration | Get Active Compose Projects
  ansible.builtin.shell: "docker compose ls -q"
  register: currentapplications
  become: true
  changed_when: false

- name: Docker | Configuration | Stop non-required projects
  ansible.builtin.shell: "docker compose -p {{ item }} down"
  with_items: "{{ currentapplications.stdout_lines | difference(applications.stdout_lines) }}"
  become: true

- name: Docker | Configuration | Remove non-required projects
  ansible.builtin.file:
    path: "{{ docker.paths.apps }}/{{ item }}"
    state: absent
  become: true
  with_items: "{{ currentapplications.stdout_lines | difference(applications.stdout_lines) }}"
