- name: Docker | Include Installation Tasks
  ansible.builtin.include_tasks:
    file: install.yml
  when: docker_install

- name: Docker | Include Configuration Tasks (Deploy)
  ansible.builtin.include_tasks:
    file: deploy_projects.yml
  when: docker_configure

- name: Docker | Include Configuration Tasks (Destroy)
  ansible.builtin.include_tasks:
    file: destroy_projects.yml
  when: docker_configure
