- name: Restart NFS
  ansible.builtin.service:
    name: nfs-server
    state: restarted
  become: true

- name: Restart SMB
  ansible.builtin.service:
    name: smb
    state: restarted
  become: true

- name: Restart Sanoid
  ansible.builtin.service:
    name: sanoid
    state: restarted
    enabled: true
  become: true

- name: Restart zed
  ansible.builtin.systemd:
    name: zfs-zed
    state: restarted
    enabled: true
  become: true