- name: Restart NFS
  ansible.builtin.service:
    name: nfs-server
    state: restarted
  become: true

- name: Restart SMB
  ansible.builtin.service:
    name: smb
    state: restarted
  become: true