docker_install: true
docker_configure: false
docker_update_socket: false
docker_config_path: changeme
docker_enable_auth: false
docker_management_group: null
docker_github_auth:
  enabled: false
  pat: changeme
docker_gitea_auth:
  enabled: false
  pat: changeme
docker_users:
  - dan
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
docker_build: never
docker_pull: missing
