docker_install: true
docker_configure: false
docker_update_socket: false
docker_config_path: changeme
docker_enable_auth: false
docker_users: changeme
docker_build: never
docker_pull: missing
docker_enable_syslog: false
docker_compose_projects: null
docker_compose_default_path: null