docker_install: true
docker_configure: false
docker_update_socket: false
docker_config_path: changeme
docker_management_group: null
docker_github_auth:
  enabled: false
  pat: changeme
docker_gitea_auth:
  enabled: false
  pat: changeme
