docker_install: # Install Docker?
docker_configure: # Configure Docker? (Deploy compose projects and daemon config)
docker_config_path: # Path to config.json configuration for root user
docker_enable_auth: # Configure github & gitea authentication
docker_users: # Users to add to docker group
docker_build: # Default value for docker build argument when running compose up -d
docker_pull: # Default value for docker pull argument when running compose up -d
docker_enable_syslog: # Enable sending container logs to syslog
docker_compose_projects: # Compose project definition (remove to skip)
  - name: # Compose project name (must match j2 compose project template filename)
    volume_data: # Configuration to be deployed into volumes (remove to skip)
      - volume: # Volume to deploy into
        src: # Source file to place into the volume (directory structure must be {project name}/{volume name}/{file})
        dest: # Destination within the volume (leave blank for root directory of volume)
        mode: # Permissions inside the volume (defaults to 0644)
        owner: # File/directory owner (defaults to 1000)
        group: # File/directory group (defaults to 1000)
        restart_container: # Container to restart upon changes detected (remove to skip)
docker_compose_default_path: # Path to directory containing compose file templates
docker_volume_data_path: # Path to directory containing volume data if required
docker_volume_set_acl: # Use to disable ACL configuration (true by default)
docker_base_path: # Use to override /var/lib/docker
docker_group_id: # Use to set non default group id (121)