docker_install: # Install Docker?
docker_configure: # Configure Docker? (Deploy compose projects and daemon config)
docker_config_path: # Path to config.json configuration for root user
docker_enable_auth: # Configure github & gitea authentication
docker_build: # Default value for docker build argument when running compose up -d
docker_pull: # Default value for docker pull argument when running compose up -d
docker_enable_syslog: # Enable sending container logs to syslog
docker_compose_projects: # Compose project definition (remove to skip)
  - name: # Compose project name (must match j2 compose project template filename)
    project_path: # Custom project specific path to j2 compose template
    volume_config:
      owner: # Defaults to root
      group: # Defaults to root
      mode: # Defaults to 0770
    create_bind_mount_volume: # Whether to create volume directory or not (default is false)
docker_compose_default_path: # Path to directory containing compose file templates
docker_base_path: # Use to override /var/lib/docker
docker_bind_mount_volume_path: # Location to create bind mount volume directories