users:
  - username: example
    password: password
    uid: 1055
    gid: 1055 # Defaults to UID value
    allow_sudo: false
    ssh_private_key:
    ssh_public_key:
    ssh_authorized_keys:
    ssh_manage_keys: false # remove authorized keys not in Ansible config