global_system:
  enable_packages: true
  enable_ssh_config: true
  enable_firewall_config: true
  enable_syslog_config: true
  enable_misc_config: true
  enable_cloud_init: true
  config_path: changeme
  packages: []
