enable_packages: true
enable_ssh_config: true
enable_firewall_config: true
enable_env_config: true
enable_motd_config: true
enable_syslog_config: true
enable_misc_config: true
enable_checkmk_agent_install: true
global_system_server_function: changeme
global_system_server_location: changeme
global_system_server_deployment_type: changeme
global_system_server_packages: []
global_system_nfs: null
global_system_checkmk_hosts: []
global_system_checkmk_install: true



# These vars are to prevent failure on unreachable hosts with no facts
ansible_facts:
  distribution_version: "N/A"
  distribution: "N/A"
  virtualization_type: "N/A"
