name: NGINX Installation
on:
  workflow_dispatch:
  repository_dispatch: 
    types: [nginx]
  push:
    paths:
      - roles/nginx/**
  schedule:
    - cron: "01 04 * * *"
jobs:
  terraform:
    uses: epichouse/workflow-templates/.github/workflows/ansible-role.yaml@main
    with:
        rolepath: "../${{ github.event.repository.name }}/roles/nginx"
        rolehosts: "nginx"
        multisite: true
    secrets:
        sudo_password: ${{secrets.SUDO_PASSWORD}}
        mastertoken: ${{secrets.MASTERTOKEN}}