name: Terraform Installation
on:
  workflow_dispatch:
  repository_dispatch: 
    types: [terraform]
  push:
    paths:
      - roles/terraform/**

jobs:
  terraform:
    uses: epichouse/workflow-templates/.github/workflows/ansible-role.yaml@main
    with:
        rolepath: "../${{ github.event.repository.name }}/roles/terraform"
        rolehosts: "terraform"
        multisite: true
    secrets:
        sudo_password: ${{secrets.SUDO_PASSWORD}}
        mastertoken: ${{secrets.MASTERTOKEN}}
        vault_password: ${{secrets.VAULT_PASSWORD}}